### ISSUE TITLE
`http.client_ip` fallback isn't appropriate by the otel spec

### ISSUE THREAD

**Issue by dbofmmbt** [davidB/axum-tracing-opentelemetry#15]
Here, the connection information is used as a fallback in case the `X-Forwarded-For` header isn't set:

https://github.com/davidB/axum-tracing-opentelemetry/blob/f0672632df09d05a8520604a901dd423de20042d/src/middleware.rs#L129-L135

The `http.client_ip` should hold the client IP, but we may be connected to a proxy instead.

From the otel spec:

> The IP address of the original client behind all proxies, if known (e.g. from [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For))

I think it would be a good idea to remove the fallback and conditionally insert this attribute to the span.

**Comment by davidB** [comment]
If we are connected to / through a proxy, the client_ip is read from `X-Forwarded-For`, else `X-Forwarded-For` is undefined and we can use the client_ip of the socket.

The issue is when proxy didn't fill the  `X-Forwarded-For` header, in this case, it's always valid (IMHO) to consider it as the client_ip (I agree it's not the "original", but anyways it's a client and the service should not be aware of if it's behind or not a proxy). In this case the issue is on the proxy side, and having the value in the client_ip could help to detect this issue.

Correct me, if didn't understand your suggestion.

**Comment by dbofmmbt** [comment]
Thanks for the explanation, @davidB. I think you're right. In any case, the current behavior is good. I hadn't thought about the cases you mentioned. I'll close this issue :smile:
