### ISSUE TITLE
Path and wildcards are not replaced

### ISSUE THREAD

**Issue by lcmgh** [davidB/axum-tracing-opentelemetry#45]
```rust
// Axum router ..
  .route(
      "/zuul/:service/*path",
      get(proxy_handler).post(proxy_handler),
  )

.......


pub async fn proxy_handler(
    Path((service, path)): Path<(String, String)>,
    State(state): State<ProxyApiState>,
    mut req: Request<Body>,
) 
```
Shown in Dynatrace as:
![image](https://user-images.githubusercontent.com/98088021/217254647-b1cf4520-aae3-4190-9812-ed207ac57edf.png)

**Comment by davidB** [comment]
It's not a bug, it's the expected feature. Like for metrics where we don't want to explode the cardinality.
Because the common usage of variable part is entity id like `/user/:userid` and metrics, trace should be grouped/aggregable under the "matched route" (eg the same that you will also define into your api / openapi). iirc it's also part of the specification of trace, but need to confirm (for the field `otel.name`, what you capture, and for the field `http.route`)

But maybe, an option could be add to allow to provide an custom function to build the `otel.name`. Currently it's 

```
let name = format!("{http_method_v} {http_route}");
```

**Comment by lcmgh** [comment]
My use case is a backend proxy that routes traffic to configured endpoints. The target endpoint/config selection depends on the `:service` path.

**Comment by lcmgh** [comment]
When proxying I would only like to replace a certain part of the path. In my case with `"/zuul/:service/*path",` I'd probably just replace `service`. For the remaining Url (`*path`) I couldn't tell which part is a parameter and which one not.

**Comment by davidB** [comment]
Making the `otel.name`  computable by a custom function require change (maybe breaking) in the current API and will introduce some kind of dynamic dispatch and a performance cost. 

But I have a workaround:
- start a new child span with the name you want
- or don't start a child span but update the `otel.name`

```rust
pub async fn proxy_handler(
    Path((service, path)): Path<(String, String)>,
    State(state): State<ProxyApiState>,
    mut req: Request<Body>,
) {
    tracing::Span::current().record("otel.name", format!("proxy {service}"));
    ...
}
```

![image](https://user-images.githubusercontent.com/10675/218332129-210a8c2b-e71c-4ce3-97a7-b01cd551ec12.png)

**Comment by ttys3** [comment]
@davidB this should be able to close? since this is working as expected.
